//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_BG_H
#define METASPRITE_BG_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define BG_TILE_ORIGIN 0
#define BG_TILE_W 8
#define BG_TILE_H 8
#define BG_WIDTH 160
#define BG_HEIGHT 144
#define BG_TILE_COUNT 230
#define BG_PALETTE_COUNT 1
#define BG_COLORS_PER_PALETTE 4
#define BG_TOTAL_COLORS 4
#define BG_MAP_ATTRIBUTES 0

BANKREF_EXTERN(BG)

extern const palette_color_t BG_palettes[4];
extern const uint8_t BG_tiles[3680];

extern const unsigned char BG_map[360];

#endif
