//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_LOGO_H
#define METASPRITE_LOGO_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define LOGO_TILE_ORIGIN 0
#define LOGO_TILE_W 8
#define LOGO_TILE_H 8
#define LOGO_WIDTH 160
#define LOGO_HEIGHT 144
#define LOGO_TILE_COUNT 139
#define LOGO_PALETTE_COUNT 1
#define LOGO_COLORS_PER_PALETTE 4
#define LOGO_TOTAL_COLORS 4
#define LOGO_MAP_ATTRIBUTES 0

BANKREF_EXTERN(LOGO)

extern const palette_color_t LOGO_palettes[4];
extern const uint8_t LOGO_tiles[2224];

extern const unsigned char LOGO_map[360];

#endif
