//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_DOWN_H
#define METASPRITE_DOWN_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define DOWN_TILE_ORIGIN 0
#define DOWN_TILE_W 8
#define DOWN_TILE_H 8
#define DOWN_WIDTH 24
#define DOWN_HEIGHT 32
#define DOWN_TILE_COUNT 8
#define DOWN_PALETTE_COUNT 1
#define DOWN_COLORS_PER_PALETTE 4
#define DOWN_TOTAL_COLORS 4

BANKREF_EXTERN(DOWN)

extern const palette_color_t DOWN_palettes[4];
extern const uint8_t DOWN_tiles[128];


#endif
