//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_IDLE_H
#define METASPRITE_IDLE_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define IDLE_TILE_ORIGIN 0
#define IDLE_TILE_W 8
#define IDLE_TILE_H 8
#define IDLE_WIDTH 24
#define IDLE_HEIGHT 32
#define IDLE_TILE_COUNT 10
#define IDLE_PALETTE_COUNT 1
#define IDLE_COLORS_PER_PALETTE 4
#define IDLE_TOTAL_COLORS 4

BANKREF_EXTERN(IDLE)

extern const palette_color_t IDLE_palettes[4];
extern const uint8_t IDLE_tiles[160];


#endif
