//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_LEFT_H
#define METASPRITE_LEFT_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define LEFT_TILE_ORIGIN 0
#define LEFT_TILE_W 8
#define LEFT_TILE_H 8
#define LEFT_WIDTH 24
#define LEFT_HEIGHT 32
#define LEFT_TILE_COUNT 11
#define LEFT_PALETTE_COUNT 1
#define LEFT_COLORS_PER_PALETTE 4
#define LEFT_TOTAL_COLORS 4

BANKREF_EXTERN(LEFT)

extern const palette_color_t LEFT_palettes[4];
extern const uint8_t LEFT_tiles[176];


#endif
