//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_RIGHT_H
#define METASPRITE_RIGHT_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define RIGHT_TILE_ORIGIN 0
#define RIGHT_TILE_W 8
#define RIGHT_TILE_H 8
#define RIGHT_WIDTH 24
#define RIGHT_HEIGHT 32
#define RIGHT_TILE_COUNT 11
#define RIGHT_PALETTE_COUNT 1
#define RIGHT_COLORS_PER_PALETTE 4
#define RIGHT_TOTAL_COLORS 4

BANKREF_EXTERN(RIGHT)

extern const palette_color_t RIGHT_palettes[4];
extern const uint8_t RIGHT_tiles[176];


#endif
