//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_UP_H
#define METASPRITE_UP_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define UP_TILE_ORIGIN 0
#define UP_TILE_W 8
#define UP_TILE_H 8
#define UP_WIDTH 24
#define UP_HEIGHT 32
#define UP_TILE_COUNT 11
#define UP_PALETTE_COUNT 1
#define UP_COLORS_PER_PALETTE 4
#define UP_TOTAL_COLORS 4

BANKREF_EXTERN(UP)

extern const palette_color_t UP_palettes[4];
extern const uint8_t UP_tiles[176];


#endif
